cli:
  # build: ./php/cli/
  image: snatch-php-cli
  ports:
    - "6070:8080"
  volumes:
    - ./:/data
    - ./php.ini-cli:/usr/local/etc/php/php.ini:ro
  links:
    - redis:redis-host
    - chrome:chrome-host
    - firefox:firefox-host
redis:
  image: daocloud.io/library/redis
  ports:
    - "6379:6379"
  # volumes:
  #   - ./data/redis:/data
chrome:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/hub
  ports:
    - "4445:4444"