cli:
  # build: ./php/cli/
  image: snatch-php-cli
  ports:
    - "6070:8080"
  volumes:
    - ./:/data
    - ./php.ini-cli:/usr/local/etc/php/php.ini:ro
  links:
    - redis:redis-host
    - mongodb:mongodb-host
    - chrome:chrome-host
    - firefox:firefox-host
redis:
  image: daocloud.io/library/redis
  ports:
    - "6379:6379"
  volumes:
    - ./data/redis:/data
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  links:
    - hub:hub
firefox:
  image: selenium/node-firefox
  links:
    - hub:hub
mongodb:
  image: daocloud.io/library/mongo
  volumes:
    - ./data/mongo:/data/db # 请记得正式环境时要挂载数据目录
  ports:
    - "37017:27017"